services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: globexpand-api
    ports:
      - "${PORT}:3000"
    env_file:
      - .env.docker
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_started
      maildev:
        condition: service_started
    command: npm run start:prod

  mysql:
    image: mysql:8.0
    container_name: globexpand-mysql
    restart: always
    env_file:
      - .env.docker
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docs/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  mongo:
    image: mongo:7.0
    container_name: globexpand-mongo
    restart: always
    env_file:
      - .env.docker
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  maildev:
    image: maildev/maildev
    container_name: globexpand-maildev
    restart: always
    env_file:
      - .env.docker
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  mysql_data:
  mongo_data:
